### ISSUE TITLE
Suggestion: Embedded Documentation or Demos

### ISSUE THREAD

**Issue by NathanPB** [vtnorton/Heartthrob#12]
~~yes, its me again~~
Last week I was contributing to [Prime React](https://github.com/primefaces/primereact) and I saw a very cool thing: They documentation is in the same repository as the code.

It may look dumb, but it actually helped me a lot during the development, because with it I could see the changes that I was doing **at live** in the docs/demos.

Now I'm working on some ESLint fixes of Heartthrob and I don't have a built-in environment to see if I'm accidentally breaking something.

I think it would be cool to include at least one demonstration of each feature within the source itself, it helps a lot in the development, especially to new contributors that don't know the structure of the project yet (kind of my case lol). Unit tests can also be helpful, but this may be discussed in another thread.

For references, I'm leaving the [Prime React repository](https://github.com/primefaces/primereact/tree/3.2.0), take a look at the ``src/showcase/`` directory.

**Comment by vtnorton** [comment]
You always have really cool suggestions and I always get excited about it and make it happen.

But, there is a problem about having the docs in the same repo: it goes beyond heartthrob itself. My plan is to release a lot of packages (must of then NPM and also a few dotNet libraries) that are hosted in different repo, like heartthrob-vision.

I do want to start automate tests, but there is few things going on that’s blocking me right now:

* I want to remove all jquery
* a few functions will need remodeling, that I’m starting as soon as I’m finish with this sass migration and px to em conversion. I will also work on the js docs as well (maybe next week)
* with that said, I don’t know how to start the tests, to be honest


Right now, what I’m doing to test is cloning the heartthrob-docs to the same folder I’ve cloned heartthrob. Inserted de main.css file into the layout while excluded the heartthrob.css file. And every time I run gulp sass it refreshes the docs css (see gulp tasks of heartthrob to understand what I mean).

Still complicated, but I will work a little to make it easier to test all of this. Will ping you when it’s ready. But for now, I don’t see the docs using the same repo as the code.

[and a little offtopic news: the plan is to make the docs in react and maybe with .md files instead of .cshtml files]

———-
vítor norton
https://vtnorton.com
No downtime for hustle-as-a-service
________________________________

**Comment by NathanPB** [comment]
Sure, nice to know your plans =)

I'm kinda upset with that jQuery too, gonna remove some later
