### ISSUE TITLE
Sugesting SASS

### ISSUE THREAD

**Issue by NathanPB** [vtnorton/Heartthrob#9]
I've been looking the project for a while and now I finally had time to do some contribution. So I cloned the repository and saw a big condensed ``heartthrob.css`` file.

The problem here is that all the CSS of the project is in a single file, and as the project grows, the file grows as well. This file has basically no indentation and almost every feature inside it.

My suggestion is to use [SASS](https://sass-lang.com).

# What is SASS?

Let the SASS website describe itself: ```Sass is the most mature, stable, and powerful professional grade CSS extension language in the world.```

And I completely agree!

# How can SASS help Heartthrob?

SASS has a blessed by god feature called ``@import``, its job is to import the SASS code of another files and condense it into the importer file. It could help a lot because so we can explode the features (alerts, menus, grids, etc) into multiple SASS files, but keep just one CSS generated file. 

So that's all I have to say. Everyone who understand CSS will have absolutely no problems in understanding SASS. All the CSS code and features can be keeped, its just more features to help the development process!

**Comment by vtnorton** [comment]
I agree. 

I love to make it old fashion [including no indentation as you saw], but SASS is way better. It was also on the backlog to do it yet this year. 

Let's do it with SASS as you suggested, but I will maintain the built files with the `.css` and `.min.css` file with those indentation [because, when working for WordPress themes or for students, it way better]. 

To do that, I'm opening a branch `feature/sass`.

**Comment by NathanPB** [comment]
> Let's do it with SASS as you suggested, but I will maintain the built files with the `.css` and `.min.css` file with those indentation [because, when working for WordPress themes or for students, it way better].

Sure, the SASS processor turns SCSS files into a minified CSS file, so I think you will have no problems with it

**Comment by vtnorton** [comment]
I deleted the branch `feature/sass` and have already started on `feature/vtn_scss`. Would love some help to put it on the best practises.

**Comment by NathanPB** [comment]
I was working in my fork with the installation of ``node-sass`` instead of ``gulp-sass``. Gonna study it later and adapt the build scripts. I already made some port about the tables for testing purposes.

**Comment by vtnorton** [comment]
Since I’m already using gulp I will prefer to keep it for now. I’m just dividing the heartthrob.css into different files and will fix some issues with it for now. If you want to send a PR (to feature/vtn_sass) to include your changes and then fork it, it will be ok for me to approve.

---
vítor norton
No downtime for Hustle-as-a-Service
https://vtnorton.com

________________________________

**Comment by NathanPB** [comment]
Sure, I'm gonna submit my PR as soon as I can

**Comment by vtnorton** [comment]
Thank you @NathanPB, I would love your help to shape it.... just needed to make it sure we are working on the same code-base.

**Comment by NathanPB** [comment]
~~I accidentally clicked the close button~~

Just sent some PRs, also (**offtopic warning**) removed the build files that should't be commited (they are generated every time)

**Comment by vtnorton** [comment]
Ok, no problem about the closed or the removed files. Thank you.

**Comment by vtnorton** [comment]
Just updated the master branch [as well the npm package] with this change. Thanks for making it happen @NathanPB
